version: '3.8'
services:
  dna-service:
    container_name: dna-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
    networks:
      - dna-network
    restart: unless-stopped

networks:
  dna-network:
    driver: bridge